version: "3.9"

services:
  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
  db:
    image: postgres:latest
    container_name: prostres_db
    restart: always
    environment:
      POSTGRES_USER: fastapi_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fastapi_db
    ports:
      - "5433:5432"



  app:
    build: .
    image: fast-api
    container_name: fastapi
    restart: always
    depends_on:
      - redis
    environment:
      DATABASE_URL: postgresql+asyncpg://fastapi_user:password@host.docker.internal:5432/fastapi_db?ssl=disable
      REDIS_URL: redis://redis:6379/0
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
   
    volumes:
      - .:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]


