version: '3.8'

services:
  web:
    build: .  # Build Django app
    container_name: fastapi_app_user_mgnt
    ports:
      - "8000:8000"
    depends_on:
      - redis
      # - db
    env_file:
      - .env  # Load environment variables from .env file
    volumes:
      - .:/app
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"


  redis:
    image: redis:latest
    container_name: redis-cache
    ports:
      - "6379:6379"

  # db:
  #   image: postgres:latest
  #   container_name: postgres-db
  #   restart: always
  #   ports:
  #     - "5432:5432"
  #   env_file:
  #     - .env  # Load DB credentials securely
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
