name: User mgnt with FastAPI

on:
  push:
    branches:
      - main
    tags:
      - "v*"  # Runs when a version tag like v1.0.0 is pushed
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests and Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Format Code with Black
        run: |
          pip install black
          black . --check

      - name: Lint with Flake8
        run: |
          pip install flake8
          flake8 . --count --max-line-length=88 --statistics

    #   - name: Run Tests
    #     run: |
    #       pip install pytest
    #       pytest

  docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v') }} # Runs only on main or version tags

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set Image Tag
        run: |
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            echo "IMAGE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "IMAGE_VERSION=latest" >> $GITHUB_ENV
          fi

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/fastapi-app:${IMAGE_VERSION} .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/fastapi-app:${IMAGE_VERSION}

          # Also push latest tag if running on main
          if [[ "$IMAGE_VERSION" == "latest" ]]; then
            docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/fastapi-app:latest ${{ secrets.DOCKER_HUB_USERNAME }}/fastapi-app:latest
            docker push ${{ secrets.DOCKER_HUB_USERNAME }}/fastapi-app:latest
          fi
