name: User mgnt with FastAPI

on:
  push:
    branches:
      - main
    tags:
      - "v*"  # Runs when a version tag like v1.0.0 is pushed
  pull_request:
    branches:
      - main

jobs:
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  format-code:
    name: Format Code with Black
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Black
        run: pip install black

      - name: Run Black
        run: black . --check

  lint-code:
    name: Lint with Flake8
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Flake8
        run: pip install flake8

      - name: Run Flake8
        run: flake8 . --count --max-line-length=88 --statistics

  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Pytest
        run: pip install pytest

    #   - name: Run Tests
    #     run: pytest

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: [format-code, lint-code, run-tests]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set Image Tag
        run: |
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            echo "IMAGE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "IMAGE_VERSION=latest" >> $GITHUB_ENV
          fi

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/simple-user-management-fastapi-app:${IMAGE_VERSION} .

  test-container:
    name: Test Docker Container
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug Image Version
        run: |
            echo "Using image version: ${IMAGE_VERSION}"

      - name: Start Docker Container
        run: |
          docker run -d -p 8000:8000 --name test-container ${{ secrets.DOCKER_USERNAME }}/simple-user-management-fastapi-app:${IMAGE_VERSION}
          sleep 5  # Wait for the container to start

      - name: Test API Health Check
        run: |
          curl --fail http://localhost:8000/health || exit 1

      - name: Stop and Remove Container
        run: docker stop test-container && docker rm test-container

  push-image:
    name: Push Docker Image
    runs-on: ubuntu-latest
    needs: test-container
    if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/simple-user-management-fastapi-app:${IMAGE_VERSION}

      - name: Push Latest Tag (if on main)
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/simple-user-management-fastapi-app:${IMAGE_VERSION} ${{ secrets.DOCKER_USERNAME }}/simple-user-management-fastapi-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/simple-user-management-fastapi-app:latest
